import Head from "next/head";
import "../styles/globals.scss";
import "bootstrap/dist/css/bootstrap.css";
import { BlockNavBar } from "../components/NavBars/BlockNavBar";
import { SSRProvider } from "@react-aria/ssr";

function MyApp({ Component, pageProps }) {
  return (
    <SSRProvider>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BlockNavBar />
      <Component {...pageProps} />
    </SSRProvider>
  );
}

export default MyApp;
