# Generated by Django 3.2.5 on 2021-07-06 14:00

from django.db import migrations

def create_test_data(apps, schema_editor):
    Game_apexlegends = apps.get_model('web_api', 'Game')
    Game_apexlegends(title="Apex Legends").save()

class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_test_data),
    ]
