# Generated by Django 3.2.5 on 2021-07-06 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0002_web_api'),
    ]

    operations = [
    ]
