# Generated by Django 3.2.5 on 2021-07-08 09:18

from django.db import migrations, models
import django.db.models.deletion

def create_test_data(apps, schema_editor):
    Game_apexlegends = apps.get_model('web_api', 'Game')
    Game_apexlegends(title="Apex Legends").save()

class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0003_web_api'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_title',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='image',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='web_api.section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='web_api.game'),
        ),
        migrations.RunPython(create_test_data),
    ]
