# Generated by Django 3.2.5 on 2021-08-16 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_app_separation'),
        ('home', '0001_app_separation'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumitems',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='albumitems',
            name='linked_page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='blog.gameblogpage'),
        ),
    ]
