# Generated by Django 3.2.5 on 2021-08-17 10:35

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210816_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumitems',
            name='root_page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_items', to='home.homepage'),
        ),
    ]
