# Generated by Django 3.2.5 on 2021-08-29 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_albumitems_root_page'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albumitems',
            options={'verbose_name': 'Album Item', 'verbose_name_plural': 'Album Items'},
        ),
    ]
